name: Deploy to GitHub Pages

# main ブランチ の push 時にこのワークフローを実行する
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # main ブランチを取得する
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js のセットアップをする
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # パッケージをインストールする
      - name: Install
        run: npm install

      # ビルドする
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_RESAS_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_RESAS_API_ENDPOINT }}
          NEXT_PUBLIC_RESAS_API_KEY: ${{ secrets.NEXT_PUBLIC_RESAS_API_KEY }}
          NEXT_PUBLIC_RESAS_API_PREFECTURES: ${{ secrets.NEXT_PUBLIC_RESAS_API_PREFECTURES }}
          NEXT_PUBLIC_RESAS_API_POPULATION: ${{ secrets.NEXT_PUBLIC_RESAS_API_POPULATION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAGES: true

      # ビルドする
      - name: Export
        run: npm run export

      # GitHub Pages にデプロイする
      - name: Deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
